name: github docker automation

on:
  push:
    branches: [ master ]
  pull_request:
    branches : [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:n 
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "abhinav7777" --password-stdin
        docker image build -t abhinav7777/dockerassignment:latest .
        docker push abhinav7777/dockerassignment:latest
